TOPDIR ?= ../..
include $(TOPDIR)/.config

$(WATCHCAT_SUPPORT)_SRC += services/net_activity_watchdog/net_activity_watchdog.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

##############################################################################
